spring:
  application:
    name: camunda
  datasource:
    url: jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
logging:
  level:
    '[org.springframework]': error
server:
    port: 8080
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  generic-properties:
      properties:
        historyTimeToLive: P1D

