spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

camunda.bpm:
  history-level: none
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  generic-properties:
      properties:
        historyTimeToLive: P1D